name = "0_nkey-api"
compatibility_date = "2024-01-01"
main = "functions/api/collect.ts"

# D1 데이터베이스 설정
[[d1_databases]]
binding = "DB"
database_name = "0_nkey_db"
database_id = "c48f0714-2a98-4b65-8c11-6e8ed118efdc"

# 환경 변수
[vars]
ADMIN_KEY = "dev-key-2024"
