name = "0_nkey-api"
compatibility_date = "2024-01-01"
main = "workers/collect.ts"

# 관찰 가능성 설정 (로그 활성화)
[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

# D1 데이터베이스 설정
[[d1_databases]]
binding = "DB"
database_name = "0_nkey_db"
database_id = "c48f0714-2a98-4b65-8c11-6e8ed118efdc"

# 환경 변수 (Workers용)
[vars]
ADMIN_KEY = "dev-key-2024"

# 비밀 환경 변수 (Workers용)
[[secrets]]
name = "NAVER_API_KEY_1"

[[secrets]]
name = "NAVER_API_SECRET_1"

[[secrets]]
name = "NAVER_CUSTOMER_ID_1"

[[secrets]]
name = "NAVER_OPENAPI_KEY_1"

[[secrets]]
name = "NAVER_OPENAPI_SECRET_1"