name = "0_nkey-workers"
compatibility_date = "2024-01-01"
main = "functions/cron.ts"

# D1 데이터베이스 설정
[[d1_databases]]
binding = "DB"
database_name = "0_nkey_db"
database_id = "c48f0714-2a98-4b65-8c11-6e8ed118efdc"

# 환경 변수
[vars]
ADMIN_KEY = "dev-key-2024"
NAVER_CLIENT_ID = "your-naver-client-id"
NAVER_CLIENT_SECRET = "your-naver-client-secret"

# 크론 트리거 설정
[[triggers]]
crons = ["0 2 * * *"]  # 매일 02:00 UTC에 실행
